# url: http://vpoola88.github.io/anita-portfolio/
production_url: http://vpoola88.github.io/anita-portfolio/

# Site settings
title: Anita Coggshall
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 31b4b1
  secondary: 31b4b1  
  secondary-dark: 333

social:
  - title: linkedin
    url: http://www.linkedin.com/in/anitacoggshall

include:      [".htaccess"]

# Build settings
markdown: kramdown
permalink: pretty